spring:
  profiles:
    active: 
    - dev #  build.version: $project.version$
---
spring:
     profiles: dev
     application:
       name: microservicecloud-config-kyrell-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-kyrell-test